##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## X|Y|Z & Dev
##
## Copyright Ⓒ Robert Mollentze (https:\\xyzand.dev)
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: ___generators
description: This project contains a set of generators to help speed up development.
publish_to: none

## -----------------------------------------------------------------------------

environment:

  sdk: ^3.0.0

## -----------------------------------------------------------------------------

dependencies:

   xyz_gen: any
   xyz_utils: any

dependency_overrides:

   xyz_gen:
    git: 
      url: https://github.com/robmllze/xyz_gen.git
   xyz_utils:
    git: 
      url: https://github.com/robmllze/xyz_utils.git